In [2]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv(
    r'C:\Users\JUAN\Desktop\.begin\tudo\vscode\projects_files\etl\coffee chain\Coffee Chain.csv')
# https://www.kaggle.com/datasets/edmund24/coffee-chain

In [3]:
df.head(5)

,Area Code,Cogs,Difference Between Actual and Target Profit,Date,Inventory,Margin,Market Size,Market,Marketing,记录数,...,Product,Profit,Sales,State,Target COGS,Target Margin,Target Profit,Target Sales,Total Expenses,Type
0,303,51,-35,2012-10-01 00:00:00.000,503,71,"""Major Market""","""Central""",46,1,...,"""Lemon""",-5,122,"""Colorado""",30,60,30,90,76,"""Decaf"""
1,970,52,-24,2012-10-01 00:00:00.000,405,71,"""Major Market""","""Central""",17,1,...,"""Mint""",26,123,"""Colorado""",30,60,50,90,45,"""Decaf"""
2,409,43,-22,2012-10-01 00:00:00.000,419,64,"""Major Market""","""South""",13,1,...,"""Lemon""",28,107,"""Texas""",30,60,50,90,36,"""Decaf"""
3,850,38,-15,2012-10-01 00:00:00.000,871,56,"""Major Market""","""East""",10,1,...,"""Darjeeling""",35,94,"""Florida""",40,60,50,100,21,"""Regular"""
4,562,72,6,2012-10-01 00:00:00.000,650,110,"""Major Market""","""West""",23,1,...,"""Green Tea""",56,182,"""California""",20,60,50,80,54,"""Regular"""

In [4]:

df.shape

(1062, 22)

In [5]:
df.columns

Index(['Area Code', 'Cogs', 'Difference Between Actual and Target Profit',
       'Date', 'Inventory', 'Margin', 'Market Size', 'Market', 'Marketing',
       '记录数', 'Product Line', 'Product Type', 'Product', 'Profit', 'Sales',
       'State', 'Target COGS', 'Target Margin', 'Target Profit',
       'Target Sales', 'Total Expenses', 'Type'],
      dtype='object')

In [6]:
df.dtypes

Area Code                                       int64
Cogs                                            int64
Difference Between Actual and Target Profit     int64
Date                                           object
Inventory                                       int64
Margin                                          int64
Market Size                                    object
Market                                         object
Marketing                                       int64
记录数                                             int64
Product Line                                   object
Product Type                                   object
Product                                        object
Profit                                          int64
Sales                                           int64
State                                          object
Target COGS                                     int64
Target Margin                                   int64
Target Profit                                   int64
Target Sales                                    int64
Total Expenses                                  int64
Type                                           object
dtype: object

In [7]:
nulls = df.isnull().sum()
nulls

Area Code                                      0
Cogs                                           0
Difference Between Actual and Target Profit    0
Date                                           0
Inventory                                      0
Margin                                         0
Market Size                                    0
Market                                         0
Marketing                                      0
记录数                                            0
Product Line                                   0
Product Type                                   0
Product                                        0
Profit                                         0
Sales                                          0
State                                          0
Target COGS                                    0
Target Margin                                  0
Target Profit                                  0
Target Sales                                   0
Total Expenses                                 0
Type                                           0
dtype: int64

In [8]:
df['Date'] = pd.to_datetime(df['Date'])
df.dtypes

Area Code                                               int64
Cogs                                                    int64
Difference Between Actual and Target Profit             int64
Date                                           datetime64[ns]
Inventory                                               int64
Margin                                                  int64
Market Size                                            object
Market                                                 object
Marketing                                               int64
记录数                                                     int64
Product Line                                           object
Product Type                                           object
Product                                                object
Profit                                                  int64
Sales                                                   int64
State                                                  object
Target COGS                                             int64
Target Margin                                           int64
Target Profit                                           int64
Target Sales                                            int64
Total Expenses                                          int64
Type                                                   object
dtype: object

In [9]:
def _replace_(x):
    return x.replace('"', '', regex=True)

In [10]:
df = _replace_(df)
df.head(5)

,Area Code,Cogs,Difference Between Actual and Target Profit,Date,Inventory,Margin,Market Size,Market,Marketing,记录数,...,Product,Profit,Sales,State,Target COGS,Target Margin,Target Profit,Target Sales,Total Expenses,Type
0,303,51,-35,2012-10-01,503,71,Major Market,Central,46,1,...,Lemon,-5,122,Colorado,30,60,30,90,76,Decaf
1,970,52,-24,2012-10-01,405,71,Major Market,Central,17,1,...,Mint,26,123,Colorado,30,60,50,90,45,Decaf
2,409,43,-22,2012-10-01,419,64,Major Market,South,13,1,...,Lemon,28,107,Texas,30,60,50,90,36,Decaf
3,850,38,-15,2012-10-01,871,56,Major Market,East,10,1,...,Darjeeling,35,94,Florida,40,60,50,100,21,Regular
4,562,72,6,2012-10-01,650,110,Major Market,West,23,1,...,Green Tea,56,182,California,20,60,50,80,54,Regular

In [11]:
df.columns

Index(['Area Code', 'Cogs', 'Difference Between Actual and Target Profit',
       'Date', 'Inventory', 'Margin', 'Market Size', 'Market', 'Marketing',
       '记录数', 'Product Line', 'Product Type', 'Product', 'Profit', 'Sales',
       'State', 'Target COGS', 'Target Margin', 'Target Profit',
       'Target Sales', 'Total Expenses', 'Type'],
      dtype='object')

In [12]:
columns_to_rename = {'Cogs':'COGS','Difference Between Actual and Target Profit':'Profit GAP',
                     'Margin':'Profit Margin','Market':'Segment','记录数':'Entries',
                     'Sales':'Revenue','Target Margin':'Target Profit Margin','Target Sales':'Target Revenue'}

df = df.rename(columns=(columns_to_rename))
df.columns

Index(['Area Code', 'COGS', 'Profit GAP', 'Date', 'Inventory', 'Profit Margin',
       'Market Size', 'Segment', 'Marketing', 'Entries', 'Product Line',
       'Product Type', 'Product', 'Profit', 'Revenue', 'State', 'Target COGS',
       'Target Profit Margin', 'Target Profit', 'Target Revenue',
       'Total Expenses', 'Type'],
      dtype='object')

In [13]:
df['Profit GAP'] = df['Profit GAP'] /100
df['Profit Margin'] = df['Profit Margin'] /100
df['Target Profit Margin'] = df['Target Profit Margin'] /100

df

,Area Code,COGS,Profit GAP,Date,Inventory,Profit Margin,Market Size,Segment,Marketing,Entries,...,Product,Profit,Revenue,State,Target COGS,Target Profit Margin,Target Profit,Target Revenue,Total Expenses,Type
0,303,51,-0.35,2012-10-01,503,0.71,Major Market,Central,46,1,...,Lemon,-5,122,Colorado,30,0.6,30,90,76,Decaf
1,970,52,-0.24,2012-10-01,405,0.71,Major Market,Central,17,1,...,Mint,26,123,Colorado,30,0.6,50,90,45,Decaf
2,409,43,-0.22,2012-10-01,419,0.64,Major Market,South,13,1,...,Lemon,28,107,Texas,30,0.6,50,90,36,Decaf
3,850,38,-0.15,2012-10-01,871,0.56,Major Market,East,10,1,...,Darjeeling,35,94,Florida,40,0.6,50,100,21,Regular
4,562,72,0.06,2012-10-01,650,1.10,Major Market,West,23,1,...,Green Tea,56,182,California,20,0.6,50,80,54,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,775,250,1.33,2013-12-01,1820,2.51,Small Market,West,70,1,...,Earl Grey,233,534,Nevada,180,1.8,100,360,94,Regular
1058,971,88,0.48,2013-12-01,817,1.33,Small Market,West,29,1,...,Earl Grey,108,236,Oregon,60,1.0,60,160,60,Regular
1059,775,294,-2.85,2013-12-01,8252,-2.94,Small Market,West,111,1,...,Green Tea,-605,33,Nevada,210,-2.1,-320,0,145,Regular
1060,503,134,0.80,2013-12-01,690,1.86,Small Market,West,41,1,...,Green Tea,180,341,Oregon,90,1.4,100,230,65,Regular
1061,435,20,-0.22,2013-12-01,218,0.25,Small Market,West,7,1,...,Green Tea,-22,48,Utah,10,0.2,0,30,40,Regular

In [14]:
df.dtypes

Area Code                        int64
COGS                             int64
Profit GAP                     float64
Date                    datetime64[ns]
Inventory                        int64
Profit Margin                  float64
Market Size                     object
Segment                         object
Marketing                        int64
Entries                          int64
Product Line                    object
Product Type                    object
Product                         object
Profit                           int64
Revenue                          int64
State                           object
Target COGS                      int64
Target Profit Margin           float64
Target Profit                    int64
Target Revenue                   int64
Total Expenses                   int64
Type                            object
dtype: object

In [15]:
df.to_csv('../../data/coffeechain_cleaned.csv')